### ISSUE TITLE
Add this Mod! PlusTiC

### ISSUE THREAD

**Issue by bigdious** [TeamTwilight/DoIAmCake#1]
This mod is an Add-on to Tinker's, similar to ExtraTic. It adds a couple of weapons as well as parts of materials from other mods we have on the server, such as Botania and Thaumcraft 6, however it does not have direct support with Twilight Forest. Testing-wise, it would be quite interesting to see how the TF materials (nagascale, fiery, knightmetal etc.) synergize with the new material parts added by this mod and it would also bring the mods present on the server closer together. While some materials may seem powerful, such as terrasteel, they mostly require having reached the endgame of that particular mod. From my testing, I haven't noticed any issues/bugs/crashes with the other mods present in the mudpack. Here's the curseforge link: https://www.curseforge.com/minecraft/mc-mods/plustic

**Comment by Tamaized** [comment]
96e2a57715593169143fc1ee88fea2a17ad2b1fb
