### ISSUE TITLE
New season mod list

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/DoIAmCake#15]
This is a list of mods that I would like to see in a new season. Of course, feel free to completely ignore some or all of them, this is just my personal opinion. ^,^

Chisel & Bits 
Clumps (so xp doesn't lag the server out like it did towards the end of 1.16.5)
Collective (dependency for mods by Serilum)
DragonDropsElytra 
Easy Villagers
EnderChests (https://www.curseforge.com/minecraft/mc-mods/enderchests)
Essentials (https://www.curseforge.com/minecraft/mc-mods/essentials) (This one I prefer above most others, solely for the fact that it adds a way to move items without using minecarts [lag], but isn't really an overpowered pipe mod either)

Iron Chest
MoreDragonEggs (purely for achievement hunting)
Natures Compass
Passthrough Signs
Reap
Supplementaries (https://www.curseforge.com/minecraft/mc-mods/supplementaries) (requires Selene Lib https://www.curseforge.com/minecraft/mc-mods/selene)

TheOneProbe (I include this one serverside because in the past I have found it doesn't work otherwise, and I rely on it quite heavily due to my eyesight being dogshit)

TorchMaster
Vanilla Excavators and Vanilla Hammers
Waystones

I would also like to see a mod like Biomes O Plenty but I understand in the past the devs have tried to not change the overworld much as this is after all a testing server, but vanilla biomes are also boring.

This is my list, do with it what you will, congrats on the beta release!! :D

**Comment by EvergreenSystems** [comment]
Chisels&Bits (https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
Clumps (https://www.curseforge.com/minecraft/mc-mods/clumps)
DragonDropsElytra (https://www.curseforge.com/minecraft/mc-mods/dragon-drops-elytra)
Easy Villagers (https://www.curseforge.com/minecraft/mc-mods/easy-villagers)
Iron Chests (https://www.curseforge.com/minecraft/mc-mods/iron-chests)
More Dragon Eggs (https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs)
Natures Compass (https://www.curseforge.com/minecraft/mc-mods/natures-compass)
Passthrough Signs (https://www.curseforge.com/minecraft/mc-mods/passthrough-signs) 
Reap (https://www.curseforge.com/minecraft/mc-mods/reap-mod)
TheOneProbe (https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
Torchmaster (https://www.curseforge.com/minecraft/mc-mods/torchmaster)
Vanilla Excavators (https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge)
Vanilla Hammers (https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers-forge)

Both hammers and excavators require MoreVanillaLib and LibX (https://www.curseforge.com/minecraft/mc-mods/morevanillalib) (https://www.curseforge.com/minecraft/mc-mods/libx)

Waystones (https://www.curseforge.com/minecraft/mc-mods/waystones)
Biomes O Plenty (https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

Including this because Drull told me to

**Comment by Drullkus** [comment]
Geodes for various ores, made by ShyNieke and MrBysco https://www.curseforge.com/minecraft/mc-mods/geore

**Comment by Drullkus** [comment]
Return of the Oreberry Bushes (Bysco) https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted
