### ISSUE TITLE
1.18 Season Modlist

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/DoIAmCake#16]
This is the pack that I am running in singleplayer, enjoy

Apotheosis : https://www.curseforge.com/minecraft/mc-mods/apotheosis
Appleskin : https://www.curseforge.com/minecraft/mc-mods/appleskin
Better Advancements : https://www.curseforge.com/minecraft/mc-mods/better-advancements
Biomes O' Plenty : https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
Bow Infinity Fix : https://www.curseforge.com/minecraft/mc-mods/bow-infinity-fix
Chisel and Bits : https://www.curseforge.com/minecraft/mc-mods/chisels-bits
Collective : https://www.curseforge.com/minecraft/mc-mods/collective
Curios : https://www.curseforge.com/minecraft/mc-mods/curios
Easy Piglins : https://www.curseforge.com/minecraft/mc-mods/easy-piglins
Easy Villagers : https://www.curseforge.com/minecraft/mc-mods/easy-villagers
Ender Tanks : https://www.curseforge.com/minecraft/mc-mods/endertanks
Essentials : https://www.curseforge.com/minecraft/mc-mods/essentials
Immersive Engineering : https://www.curseforge.com/minecraft/mc-mods/immersive-engineering
Iron Chests : https://www.curseforge.com/minecraft/mc-mods/iron-chests
Just Mob Heads : https://www.curseforge.com/minecraft/mc-mods/just-mob-heads
Mob Grinding Utils : https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils
Natures Compass : https://www.curseforge.com/minecraft/mc-mods/natures-compass
Packing Tape : https://www.curseforge.com/minecraft/mc-mods/packing-tape
Passthrough Signs (config to work with item frames as well) : https://www.curseforge.com/minecraft/mc-mods/passthrough-signs
Polymorph : https://www.curseforge.com/minecraft/mc-mods/polymorph
Pride Flags : https://www.curseforge.com/minecraft/mc-mods/pride-flags
Quark : https://www.curseforge.com/minecraft/mc-mods/quark
Quark Oddities : https://www.curseforge.com/minecraft/mc-mods/quark-oddities
Reap mod : https://www.curseforge.com/minecraft/mc-mods/reap-mod
Ring of Repair : https://www.curseforge.com/minecraft/mc-mods/ring-of-repair-forge
ShetiPhianCore (dependency for endertanks) : https://www.curseforge.com/minecraft/mc-mods/shetiphiancore
Silent Gear : https://www.curseforge.com/minecraft/mc-mods/silent-gear
Silent Lib (silent gear dependency) : https://www.curseforge.com/minecraft/mc-mods/silent-lib
Snow! Real Magic! : https://www.curseforge.com/minecraft/mc-mods/snow-real-magic
Sophisticated Backpacks : https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
Terrablender (BOP dependency) : https://www.curseforge.com/minecraft/mc-mods/terrablender
Torchmaster : https://www.curseforge.com/minecraft/mc-mods/torchmaster
Trash Cans : https://www.curseforge.com/minecraft/mc-mods/trash-cans
Tree Harvester : https://www.curseforge.com/minecraft/mc-mods/tree-harvester
     (This one actually works with modded trees, unlike reap)
Waystones : https://www.curseforge.com/minecraft/mc-mods/waystones
Wither Skeleton Totem : https://www.curseforge.com/minecraft/mc-mods/wither-totem

Along with of course mods like voidscape, ornamental, undergarde, etc.

I love all of these mods, but ofc feel free to pick and choose as you see fit

**Comment by EvergreenSystems** [comment]
And this : https://www.curseforge.com/minecraft/mc-mods/boss-rifts : because Jodi

**Comment by makazuwr32** [comment]
I'd say no need for Apotheosis mod. Or at least enchantment module.
Too overcomplicates enchantment system.

Quark might be fine. Especially its trash feature.

Also i'd like to add another mod to this suggestion:
Storage Drawers : [https://www.curseforge.com/minecraft/mc-mods/storage-drawers](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)

**Comment by EvergreenSystems** [comment]
Mystical Agriculture is another one that I would toss in
https://www.curseforge.com/minecraft/mc-mods/cucumber
https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

**Comment by bleh1245** [comment]
Appleskin, Iron Chests, Storage Drawers, and Waystones have already been mentioned

Curious Elytra and Curious Shulker Boxes would be really nice (both require Curios API and the former requires Caelus API. Author claims the former still works with 1.18.2, dunno about the latter but I would assume the same)
https://www.curseforge.com/minecraft/mc-mods/curious-elytra
https://www.curseforge.com/minecraft/mc-mods/curious-shulker-boxes
https://www.curseforge.com/minecraft/mc-mods/curios
https://www.curseforge.com/minecraft/mc-mods/caelus

Customizable Elytra would be neat as well
https://www.curseforge.com/minecraft/mc-mods/customizable-elytra

Construction Wand is a big time QoL for me
https://www.curseforge.com/minecraft/mc-mods/construction-wand

A Vein Mining enchantment mod would be great for late game.
https://www.curseforge.com/minecraft/mc-mods/vein-mining
Here's the world config settings I have for personal balance, though feel free to change anything as you see fit:
https://i.imgur.com/SFdMcjb.png
https://i.imgur.com/6VhUgIq.png
(Anything not shown is left as default)

Edit: gonna add one more:
https://www.curseforge.com/minecraft/mc-mods/champions
