### ISSUE TITLE
1.18.2 Updated Modlist Suggestion

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/DoIAmCake#17]
This is an updated list of mods for 1.18.2 that _I_ think would be nice to have. Do with this what you will:

Artifacts: Adds numerous curios with unique attributes. 
Dependencies: Curios API, ExpandAbility
https://www.curseforge.com/minecraft/mc-mods/artifacts

Balm: Dependency for Waystones
https://www.curseforge.com/minecraft/mc-mods/balm

Chipped: Adds a variety of alternative textures for blocks, including glass, lanterns, and _many_ others. 
Dependencies: CTM
https://www.curseforge.com/minecraft/mc-mods/chipped

Clumps: A performance fix for xp, combines numerous xp entities into a few larger xp entities, reducing the load on the server. 
https://www.curseforge.com/minecraft/mc-mods/clumps

Collective: A dependency for Serilum's mods.
https://www.curseforge.com/minecraft/mc-mods/collective

Cosmetic Armor Reworked: Allows the player to wear one set of armor and visually display another, longtime favorite. 
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

Crying Ghasts: Small mod, allows ghasts to drop the occasional tear without dying. 
Dependencies: Collective
https://www.curseforge.com/minecraft/mc-mods/crying-ghasts

Crying Portals: Small mod, allows nether portals to be created with crying obsidian.
Dependencies: Collective
https://www.curseforge.com/minecraft/mc-mods/crying-portals

CTM: It's CTM.
https://www.curseforge.com/minecraft/mc-mods/ctm

Curios API: Adds curio slots, dependency for mods that add curios (such as Artifacts). Has compat with TF.
https://www.curseforge.com/minecraft/mc-mods/curios

Easy Villagers: Qol mod that reduces lag related to villagers (and makes dealing with them much easier). 
https://www.curseforge.com/minecraft/mc-mods/easy-villagers

Easy Piglins: Same principle as Easy Villagers but for piglin trading.
https://www.curseforge.com/minecraft/mc-mods/easy-piglins

EnderTanks: Tanks that have similar properties to ender chests, allowing for easier collection and storage of fluid. Useful when combined with Tinkers Construct for fuel collection.
Dependencies: ShetiPhianCore
https://www.curseforge.com/minecraft/mc-mods/endertanks

Essentials: adds small qol automation features, such as item pipes and sorting hoppers.
https://www.curseforge.com/minecraft/mc-mods/essentials

ExpandAbility: Library mod
https://www.curseforge.com/minecraft/mc-mods/expandability

Explorers Compass: Craftable compass that points to a specific structure. Sister mod to Natures Compass
https://www.curseforge.com/minecraft/mc-mods/natures-compass

Feature NBT Deadlock Be Gone: Dependency for Repurposed Structures.
https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone

Gaia (assuming it is ready)

GeOre: Geodes, but for specific ores. 
https://www.curseforge.com/minecraft/mc-mods/geore

Glassential: Adds a few new types of glass with special properties.
Dependencies: CTM
https://www.curseforge.com/minecraft/mc-mods/glassential

Hyle: Dependency for Unearthed.
https://www.curseforge.com/minecraft/mc-mods/hyle

Immersive Engineering: Immersive tech mod, has compat with TF.
https://www.curseforge.com/minecraft/mc-mods/immersive-engineering

Infinity Water Bucket: allows for enchanting a water bucket (no other fluids) with infinity, allowing for infinite placing of water without refilling the bucket. Useful if you are weird like me and like flooding structures.
https://www.curseforge.com/minecraft/mc-mods/infinity-water-bucket

Iron Chests: Chest upgrades that allow chests to hold more, high-tier qol mod.
https://www.curseforge.com/minecraft/mc-mods/iron-chests

Just Mob Heads: Allows all mobs to drop heads. 
Dependencies: Collective
https://www.curseforge.com/minecraft/mc-mods/just-mob-heads

Magical Jewelry: Allows hostile mobs to drop curios that bestow potion effects for a limited time.
Dependencies: Curios API
https://www.curseforge.com/minecraft/mc-mods/magical-jewelry

Mantle: Library for Tinkers Construct
https://www.curseforge.com/minecraft/mc-mods/mantle

MelonGolem: Tamas melons

MinecraftCapes: Adds customizable capes similar to skins. Purely cosmetic.
https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod

Mob Grinding Utils: Adds various blocks that make grinding much easier (and adds liquid xp).
https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils

More Dragon Eggs: Spawns a dragon egg every time the dragon is killed, not just once. GIves slower players a chance to have the egg. 
https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs

Moyai: Decorative Moyai, nothing more.
https://www.curseforge.com/minecraft/mc-mods/moyai

Natures Compass: Craftable compass that points to a specific biome.
https://www.curseforge.com/minecraft/mc-mods/natures-compass

Ornamental: Of course

Passthrough Signs: Allows the player to click through a sign to interact with something behind, typically chests. Please configure to also allow clicking through item frames :)
https://www.curseforge.com/minecraft/mc-mods/passthrough-signs

Polymorph: Multiple mods invites crafting conflicts, polymorph allows the player to bypass said conflicts.
https://www.curseforge.com/minecraft/mc-mods/polymorph

Repurposed Structures: Adds ruin structures to the overworld, breaks up the monotony a bit. Config needs to be edited serverside to properly blacklist the TF.
Dependencies: Feature NBT Deadlock Be Gone
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

Sophisticated Backpacks: Adds upgradable backpacks with modular augments.
Dependencies: Sophisticated Core, Curios API
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

Sophisticated Core: Dependency for Sophisticated Backpacks
https://www.curseforge.com/minecraft/mc-mods/sophisticated-core

SwingThroughGrass: Allows the player to hit mobs through (very annoying) tall grass and flowers. 1.18.1 version works on 1.18.2
https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass

Tinkers Construct: Tinkers Construct
Dependencies: Mantle
https://www.curseforge.com/minecraft/mc-mods/tinkers-construct

The Undergarden: Of course

Torchmaster: Adds a couple of items for lighting and mob-spawn prevention.
https://www.curseforge.com/minecraft/mc-mods/torchmaster

Tree Harvester: Cut trees down in a single hit
Dependencies: Collective
https://www.curseforge.com/minecraft/mc-mods/tree-harvester

Unearthed: Adds numerous stonetypes for natural generation. Extensive, I love it but it adds a lot. Does _not_ change generation otherwise, just replaces some (but not all) stone with other types of stone.
Dependencies: Hyle
https://www.curseforge.com/minecraft/mc-mods/unearthed

Voidscape: Of course

Waystones: Stones that the player can teleport between. If possible please disable xp cost for overworld transport, but leave in place for interdimensional transport.
https://www.curseforge.com/minecraft/mc-mods/waystones

Wither Skeleton Totem: Adds a craftable (and rarely generating in the nether) block that increases looting for the player in its vicinity, but also increases damage delt by mobs. Useful for grinders.
https://www.curseforge.com/minecraft/mc-mods/wither-totem

**Comment by EvergreenSystems** [comment]
Personal add: WIldfire Gender Mod, do with it what you will. Say what ya want but gender validation is nice
https://www.curseforge.com/minecraft/mc-mods/female-gender-forge

**Comment by Tamaized** [comment]
This is a testing server, that doesnt need to be in a testing server.

**Comment by StupidityOfTheUser** [comment]
Ars Nouveau: A magic mod which features custom spellcrafting and magic-based machinery, all respectful of FTB claims

Dependencies: Curios API, Patchouli
