### ISSUE TITLE
Once again, I come to make a modpack. 1.19

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/DoIAmCake#19]
My list of preferred mods for 1.19. Unfortunately, at this time mods such as Immersive Engineering and Tinkers Construct are not ported, hopefully those come in the near future. Till then, here we are! I do also recommend one datapack, listed at the end. 

Additional Structures: Adds new structures into the game, such as ruined jungle pyramids and ~150 others!
https://www.curseforge.com/minecraft/mc-mods/additional-structures/files/all?filter-game-version=1738749986%3a73407 

Appleskin: Displays extra hunger and saturation info.
https://www.curseforge.com/minecraft/mc-mods/appleskin/files/all?filter-game-version=1738749986%3a73407 

Architectury API: Dependency mod for Better Animals Plus
https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all?filter-game-version=1738749986%3a73407 

Bad beacon: Beacons, but Androsa made them evil.
https://www.curseforge.com/minecraft/mc-mods/bad-beacon/files/3857217 

Balm: Dependency for waystones.
https://www.curseforge.com/minecraft/mc-mods/balm/files/all?filter-game-version=1738749986%3a73407 

Better Animals Plus: Adds multiple passive and hostile mobs into the world, and some associated loot and food. Boars are chaotic.
Requires: Architectury API, Curios API
https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus/files/all?filter-game-version=1738749986%3a73407 

Collective: Required dependency of mods made by Serilum.
https://www.curseforge.com/minecraft/mc-mods/collective/files/all?filter-game-version=1738749986%3a73407 

Cosmetic Armor Reworked: The 1.18+ port of Cosmetic Armor, allows a player to wear one set of armor and visibly display another. Funny with the /coshat command.
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked/files/all?filter-game-version=1738749986%3a73407 

Crying Ghasts: Allows ghasts to occasionally drop a ghast tear (configurable player distance and tick time between drops). Nice when farming ghasts, wonder if it would extend to carminite ghastlings?
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/crying-ghasts/files/all?filter-game-version=1738749986%3a73407 

Crying Portals: Allows nether portals to contain crying obsidian as well as regular obsidian.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/crying-portals/files/all?filter-game-version=1738749986%3a73407 

Curios API: Adds slots for charms, backpacks, etc. Dependency for multiple mods.
https://www.curseforge.com/minecraft/mc-mods/curios/files/all?filter-game-version=1738749986%3a73407 

Easy Piglins: Easy villagers, but for piglin bartering! Very funny
https://www.curseforge.com/minecraft/mc-mods/easy-villagers/files/all?filter-game-version=1738749986%3a73407 

Easy Villagers: The classic villager entrapment mod, cuts down on villager AI lag and makes villagers less annoying.
https://www.curseforge.com/minecraft/mc-mods/easy-villagers/files/all?filter-game-version=1738749986%3a73407 

Essentials: Adds multiple redstone utils, including high-throughput hoppers and item shifters. I really highly request this one, I use the item shifter a lot and my only vanilla alternative is the minecart. I humbly beg you, please Giz
https://www.curseforge.com/minecraft/mc-mods/essentials/files/all?filter-game-version=1738749986%3a73407 

Glassential: Adds different glass variants, including redstone glass, glowstone glass, and etherial glass (glass solid only to, or everything but players). Fun for mob farms.
https://www.curseforge.com/minecraft/mc-mods/glassential/files/all?filter-game-version=1738749986%3a73407

Inventory Sorter: A qol mod that oddly needs to be on both server and client to work, allows the player to sort their inventory with a keybind. Makes life less chaotic.
https://www.curseforge.com/minecraft/mc-mods/inventory-sorter/files/all?filter-game-version=1738749986%3a73407 

Iron Chests: The classic storage solution for all your hoarding needs! 
https://www.curseforge.com/minecraft/mc-mods/iron-chests/files/all?filter-game-version=1738749986%3a73407 

Just Mob Heads: Allows mobs to drop their head upon death. Configurable rarity.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files/all?filter-game-version=1738749986%3a73407 

Large Ore Deposits: Adds super rare, large deposits of ore in the overworld. 
Dependencies: ForgeEndertech Library
https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits/files/all?filter-game-version=1738749986%3a73407 

MinecraftCapes Mod: Allows players to design and wear custom capes, only visible to others with the mod. 
https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod/files/all?filter-game-version=1738749986%3a73407 

Mooshroom Spawn: Allows for very rare mooshroom spawns in non-mushroom biomes w/ other cow spawns.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/mooshroom-spawn/files/all?filter-game-version=1738749986%3a73407 

Mooshroom Tweaks: Allows brown mooshrooms to spawn naturally.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/mooshroom-tweaks/files/all?filter-game-version=1738749986%3a73407 

Nether Portal Spread: When a nether portal is lit, the nether leaches into the overworld over time. Configurable, and can be halted by placing four coal blocks in the vicinity of the portal.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread/files/all?filter-game-version=1738749986%3a73407 

Passthrough Signs: Allows the player to interact with blocks behind signs, and some other configurable things (paintings, banners, item frames). Please enable item frames in the config for my sanity’s sake
https://www.curseforge.com/minecraft/mc-mods/passthrough-signs/files/all?filter-game-version=1738749986%3a73407 

Random Bone Meal Flowers: When the ground is bonemealed, allows for any flowers to generate, not just the three supported by vanilla. Can include modded flowers.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files/all?filter-game-version=1738749986%3a73407 

Reap: Allows one to harvest crops by rightclicking, replanting a new plant w/out breaking it. Nice for community farms and mass-harvesting. Has a very inferior tree-harvesting mechanic, though I recommend using Selirums mod instead as it plays nice with other mod’s axes and has better checks for trees.
https://www.curseforge.com/minecraft/mc-mods/reap-mod/files/all?filter-game-version=1738749986%3a73407 

Repurposed Structures: Adds variants of pre-existing vanilla structures into different biomes and dimensions, such as overworld cities (wood end cities), nether pyramids and temples, and overworld fortresses. Config needs to be tweaked to blacklist the Twilight Forest last I checked.
Requirements:
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/all?filter-game-version=1738749986%3a73407 

Sophisticated Backpacks: Adds highly configurable and modular backpacks, with a lot of fun modules to make life much easier.
Requirements: Curios API, Sophisticated Core
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/all?filter-game-version=1738749986%3a73407 

Sophisticated Core: Library dependency for Sophisticated Backpacks.
https://www.curseforge.com/minecraft/mc-mods/sophisticated-core/files/all?filter-game-version=1738749986%3a73407 

Starlight: Spiritual successor to phosphor, rewrites and streamlines Minecraft’s lighting engine and makes life much easier.
https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files/all?filter-game-version=1738749986%3a73407 

SuperMartijn642’s Core Library: Dependency for Trashcans.
https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib/files/all?filter-game-version=1738749986%3a73407 

Torchmaster: Adds megatorches and dreadlamps, which disallow hostile and passive spawning respectively within a configurable radius, default 64 blocks. Makes creating twilight-esque dimly lit bases in the overworld possible, and reduces creeper holes.
https://www.curseforge.com/minecraft/mc-mods/torchmaster/files/all?filter-game-version=1738749986%3a73407 

Trashcans: Adds, well, trashcans. Nice and simple.
Requires: SuperMartijn642’s core library
https://www.curseforge.com/minecraft/mc-mods/trash-cans/files/all?filter-game-version=1738749986%3a73407 

Tree Harvester: The best treefelling mod I have seen in a while.
Requires: Collective
https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files/all?filter-game-version=1738749986%3a73407 

Waystones: Allows for teleportation between waystones, and sharestone networks for farms and etc. Very useful for transportation of animals w/ leads.
Requires: Balm
https://www.curseforge.com/minecraft/mc-mods/waystones/files/all?filter-game-version=1738749986%3a73407 

Wildfire’s Gender mod: Adds visual gender things, ‘tis nice.
https://www.curseforge.com/minecraft/mc-mods/female-gender-forge/files/all?filter-game-version=1738749986%3a73407 

Datapacks:

Towers of the Wild Reworked: Adds towers imitating the towers in Legend of Zelda: BOTW. Can be configured to be compatible with waystones! 
https://www.curseforge.com/minecraft/texture-packs/towers-of-the-wild-reworked-datapack

**Comment by EvergreenSystems** [comment]
More Dragon Eggs: Causes the ender dragon to drop an egg every time it is killed. Serves no purpose other than for achievement hunting, as the ender dragon is usually killed within a day of the start of the season and thus the "The Next Generation" advancement is completely gatekept by whoever rushes the end. Makes me, a slow player, happy.
https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs/files/all?filter-game-version=1738749986%3a73407

**Comment by jodlodi** [comment]
Boss Rifts 🙂
https://www.curseforge.com/minecraft/mc-mods/boss-rifts

**Comment by Drullkus** [comment]
Shield Parry https://www.curseforge.com/minecraft/mc-mods/parry/files

**Comment by EvergreenSystems** [comment]
Configured, to allow players to configure things like JEI in-game without having to go out to the config folder and reload.
Needs to be on both server and client to work
https://www.curseforge.com/minecraft/mc-mods/configured/files

**Comment by Drullkus** [comment]
[This mod, Item Borders, looks cool!](https://www.curseforge.com/minecraft/mc-mods/item-borders)

![image](https://i.imgur.com/xA8PNc9.png)

Could make for a worthy inclusion among other suggestions for client mods, if we were to compile a list to post on the Discord

**Comment by ThousandFields** [comment]
As for client side mods, I would also like to suggest a visual improvement and QoL mod.


[Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips):
This mod will add borders to item tooltips. The borders change depending on the type of item and any keywords in its name (or manually whitelisted).

The [Eclectic Trove](https://www.curseforge.com/minecraft/texture-packs/eclectic-trove-legendary-tooltips) addon provides a handful of custom borders for various themes of items. A few of these include a hell border for nether items, a geometric purple border for end items, and an angelic border for items such as golden apples or the elytra.

As this may be currently the only addon for Legendary Tooltips, and that TF has clearly defined themes for some items, it may be worth the attention of an artist willing to create a TF addon for this mod.


[Item Highlighter](https://www.curseforge.com/minecraft/mc-mods/item-highlighter):
This mod will simply add a small indicator to items that were new to the inventory since the last time it was opened. The indicator disappears upon inventory closure or the item being hovered over.


Both of these mods and Drull's suggestion for Item Borders are all created by the same developer and require the dependency [Iceberg](https://www.curseforge.com/minecraft/mc-mods/iceberg)

**Comment by EvergreenSystems** [comment]
I forgot a dependency, silly me
ForgeEndertech: dependency for Adlods
https://www.curseforge.com/minecraft/mc-mods/forgeendertech/files/all?filter-game-version=1738749986%3a73407

**Comment by EvergreenSystems** [comment]
Ok, after running a quick test, the game will load properly with the latest version of every serverside mod in this list, including the ones that Drull and Jodi recommended (I did not test fields mods as they are clientside), except for the inventorysorter mod (its stuck back before breaking forge changes).

**Comment by StupidityOfTheUser** [comment]
FramedBlocks: Okay hear me out - although there is significant cross-redundancy between this and Ornamental, each provide useful features that the other lacks - FramedBlocks allows any *solid* block to take the forms of divided blocks, fences, walls and doors, but the Ornamental mods provide us with Saddle Doors, proper heights for Grass Paths and new golems to take on our adventures.
https://www.curseforge.com/minecraft/mc-mods/framedblocks/files/3919861

**Comment by EvergreenSystems** [comment]
Better advancements has made it to 1.19.2
https://www.curseforge.com/minecraft/mc-mods/better-advancements/files/

**Comment by EvergreenSystems** [comment]
Seeing as how tinkers construct has not yet made the jump, this is a small alternative solution for mining tools (namely hammers and excavators): Simply Tools. https://www.curseforge.com/minecraft/mc-mods/simply-tools/files

It has one required dependency: LibX. https://www.curseforge.com/minecraft/mc-mods/libx/files
and an optional dependency with JEI plugins: MoreVanillaLib: https://www.curseforge.com/minecraft/mc-mods/morevanillalib/files

It also has an adjacent mod, MoreVanillaTools. This allows for tools made of other materials (redstone, lapis, etc).
https://www.curseforge.com/minecraft/mc-mods/morevanillatools/files
This has the same dependencies, LibX and MoreVanillaLib
