### ISSUE TITLE
Davincis Vessels  (Mod Suggestion)

### ISSUE THREAD

**Issue by Mustached-Man** [TeamTwilight/DoIAmCake#3]
This mod is an alternate version of the Archimedes' Ships mod which supports 1.12.2.
It adds nothing more then a few other elements to the game along with the ship helm, 
This mod allows you to create ships and fly

To change what kind of blocks that can interact with the ship can be reconfigured in the config file. More information will be available in the link below.

Davincis Vessels:
 https://www.curseforge.com/minecraft/mc-mods/davincis-vessels

MovingWorld (required to run Davincis Vessels):
https://www.curseforge.com/minecraft/mc-mods/movingworld/files
 
Here are the questions that were asked about the mod for your convenience.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Q: Will you make it possible for me to walk on moving ships?

A: The chances are low, if it does happen it will not be very soon, 
it's a large amount of work to hook into minecraft's collision system and tell it to behave 
differently just for me.


Q: Working blocks on ships?

A: Yes, eventually but they will be limited, and you will need to tell the mod which ones 
work in the config file. For example, you wouldn't want buildcraft quarries working by default 
because that's not a good idea, but you would want engines working because that's awesome.


Q: What's MovingWorld?

A: A dependency that stores information on how to build ships as well as render them, 
it's important. DV will not work without it!


Q: How big can I make a ship?

A: 2048 blocks is the default max, this can be configured.


Q: Does it work with *MOD HERE*?

A: It should, but I can't guarantee anything, if in doubt make a test world, 
check if it works. If it does, great! If it doesn't, make a bug report.


Q: How do I install?

A: First install the latest version of forge, then install the latest builds of both 
MovingWorld, and DV

**Comment by RZOK** [comment]
I can see this being used for griefinf claims

**Comment by RZOK** [comment]
While a cool mod, this definitely poses the threat of claim greifing on multiplayer servers.

**Comment by Mustached-Man** [comment]
> While a cool mod, this definitely poses the threat of claim greifing on multiplayer servers.

Hmm, good point

**Comment by ThousandFields** [comment]
I do agree that this is a good mod and wouldn't greatly hinder the size of the modpack. Although, is it something _needed_ for the server or has compatibility/integration with Twilight Forest?

**Comment by Mustached-Man** [comment]
> I do agree that this is a good mod and wouldn't greatly hinder the size of the modpack. Although, is it something _needed_ for the server or has compatibility/integration with Twilight Forest?

Well not needed, i thought of this mod as a transportation option for those who don't have the materials or advanced items needed to  do so.
