### ISSUE TITLE
Mod Suggestion: Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by RZOK** [TeamTwilight/DoIAmCake#4]
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
Cosmetic Armor Reworked is a small mod that adds vanity armor slots, armor placed in those slots does nothing except shows up on the player model instead of the player's actually equipped armor.
It also adds visibility toggles to every armor and bauble slot.

**Comment by RZOK** [comment]
Another mod I would like to suggest that fits very nicely with Cosmetic Armor Reworked is Extra Bit Manipulation (https://www.curseforge.com/minecraft/mc-mods/extra-bit-manipulation), it adds tools to help with Chisel & Bits, along with armor that you can modify the look of with Bits.

**Comment by bigdious** [comment]
Oh god, the vanity armor slots would be a godsent. Imagine walking around looking like you have fiery armor on without actually needing to have it on.

**Comment by bigdious** [comment]
Afaik the armor from Extra bit manipulation cause lag issues tho. Well, clientside, but still.
