### ISSUE TITLE
Mod Suggestion: Thaumic Periphery

### ISSUE THREAD

**Issue by RZOK** [TeamTwilight/DoIAmCake#5]
https://www.curseforge.com/minecraft/mc-mods/thaumic-periphery
A small Thaumcraft 6 addon that mainly adds more Baubles to the game.

**Comment by bigdious** [comment]
Honestly more baubles, especially more variability with baubles would be quite nice for the server. Looking at the mod I can definitely see some fun uses for some baubles.
