### ISSUE TITLE
Mod suggestion: vivecraft forge extensions

### ISSUE THREAD

**Issue by TropheusJ** [TeamTwilight/DoIAmCake#6]
Vivecraft is a mod that allows the user to play Minecraft in virtual reality. A server mod is not required to use it but it enhances the experience by:
Allowing short-range teleportation for a comfortable experience
Allows other players on the server using vivecraft to see the VR player’s movements

And the mod, as far as I know, is very lightweight. It does not have a direct interaction with twilight forest but I think it would allow a niche group of people to have an even better experience. Because of the lightweight of it, it would not have a noticeable affect on the average player. And (I think) it is very configurable. You can enable/disable many aspects of it including teleportation, if that is a big deal. It can be found on the vivecraft website under the downloads tab (http://www.vivecraft.org/downloads/) as the “VFE 1.12.X” (1.12 version)

**Comment by Drullkus** [comment]
The scope of the modpack is for server playing-testing the Twilight Forest, Vivecraft unfortunately doesn't have any relation to this. However looks like it can be on clients just fine so if you want to play on our server with client-only VR things then that's fine.

**Comment by TropheusJ** [comment]
Alright, thanks for the response.
